#!/bin/bash

CMD=$1
APP_VERSION=$2
TIMESTAMP=$3
NAMESPACE=$4

function print_howto() {
    echo ""
}

if [ "$CMD" = "" ]; then
    echo -e "CMD cannot be blank"
    print_howto
    exit 1
fi

if [ "$APP_VERSION" = "" ]; then
    echo -e "APP_VERSION cannot be blank"
    print_howto
    exit 1
fi

if [ "$TIMESTAMP" = "" ]; then
    echo -e "TIMESTAMP cannot be blank"
    print_howto
    exit 1
fi

if [ "$NAMESPACE" == "" ]; then
    echo -e "NAMESPACE cannot be blank"
    print_howto
    exit 1
fi

source ./pamb-base.sh

eval ${CMD}